
# 1. Sadece senin istediğin kuralları çalıştırır, diğer her şeyi kapatır
only_rules:
  - empty_count     # .count == 0 yerine .isEmpty zorunlu tutar
  - force_cast      # 'as!' kullanımını yasaklar

# 2. Taranacak klasör
included:
  - TestJenkins

# 3. Taranmayacak klasörler
excluded:
  - Pods
  - DerivedData
