# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :run_tests do
    scan(
      scheme: "TestJenkins",
      device: "iPhone 16",
      only_testing: "TestJenkinsTests",
      output_directory: "fastlane/test_output",
      output_types: "junit",
      # Dosya adını açıkça belirtiyoruz:
      output_files: "report.xml" 
    )
  end
end
